# Ingress
{{- if .Values.ingress.enabled }}

{{- if .Values.ingress.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`{{ .Values.ingress.ingressRoute.host }}`) && PathPrefix(`/{{ .Values.ingress.prefix }}/solana`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-solana-test-validator
          port: 8899
    - match: Host(`{{ .Values.ingress.ingressRoute.host }}`) && PathPrefix(`/{{ .Values.ingress.prefix }}/solana-ws`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-solana-test-validator
          port: 8900
    - match: Host(`{{ .Values.ingress.ingressRoute.host }}`) && PathPrefix(`/{{ .Values.ingress.prefix }}/solana-prometheus-exporter`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-solana-test-validator
          port: 9179

    - match: Host(`{{ .Values.ingress.ingressRoute.host }}`) && PathPrefix(`/{{ .Values.ingress.prefix }}/prometheus`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-prometheus
          port: 9090

    - match: Host(`{{ .Values.ingress.ingressRoute.host }}`) && PathPrefix(`/{{ .Values.ingress.prefix }}/grafana`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-grafana
          port: 3000

{{- else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Values.namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Values.ingress.prefix }}/solana
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-solana-test-validator
            port:
              number: 8899
      - path: /{{ .Values.ingress.prefix }}/solana-ws
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-solana-test-validator
            port:
              number: 8900
      - path: /{{ .Values.ingress.prefix }}/solana-prometheus-exporter
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-solana-test-validator
            port:
              number: 9179
      - path: /{{ .Values.ingress.prefix }}/prometheus
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-prometheus
            port:
              number: 9090
      - path: /{{ .Values.ingress.prefix }}/grafana
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-grafana
            port:
              number: 3000
{{- end }}
{{- end }}
