scrape_configs:
  # - job_name: 'node-exporter'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  - job_name: 'solana-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9179']
